// flow-typed signature: e486460a0415d0f4345a5854ffe885cb
// flow-typed version: <<STUB>>/draft-js-local-storage_v^0.0.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-local-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-local-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-local-storage/lib/cache' {
  declare module.exports: any;
}

declare module 'draft-js-local-storage/lib/DraftStore' {
  declare module.exports: any;
}

declare module 'draft-js-local-storage/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-local-storage/lib/util' {
  declare module.exports: any;
}

declare module 'draft-js-local-storage/src/cache' {
  declare module.exports: any;
}

declare module 'draft-js-local-storage/src/DraftStore' {
  declare module.exports: any;
}

declare module 'draft-js-local-storage/src/index' {
  declare module.exports: any;
}

declare module 'draft-js-local-storage/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-local-storage/lib/cache.js' {
  declare module.exports: $Exports<'draft-js-local-storage/lib/cache'>;
}
declare module 'draft-js-local-storage/lib/DraftStore.js' {
  declare module.exports: $Exports<'draft-js-local-storage/lib/DraftStore'>;
}
declare module 'draft-js-local-storage/lib/index.js' {
  declare module.exports: $Exports<'draft-js-local-storage/lib/index'>;
}
declare module 'draft-js-local-storage/lib/util.js' {
  declare module.exports: $Exports<'draft-js-local-storage/lib/util'>;
}
declare module 'draft-js-local-storage/src/cache.js' {
  declare module.exports: $Exports<'draft-js-local-storage/src/cache'>;
}
declare module 'draft-js-local-storage/src/DraftStore.js' {
  declare module.exports: $Exports<'draft-js-local-storage/src/DraftStore'>;
}
declare module 'draft-js-local-storage/src/index.js' {
  declare module.exports: $Exports<'draft-js-local-storage/src/index'>;
}
declare module 'draft-js-local-storage/src/util.js' {
  declare module.exports: $Exports<'draft-js-local-storage/src/util'>;
}
