// flow-typed signature: e1210d93bf0b971c3f3cc7dddd3b7c25
// flow-typed version: <<STUB>>/draft-js-compact_v0.0.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-compact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-compact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-compact/lib/compress' {
  declare module.exports: any;
}

declare module 'draft-js-compact/lib/expand' {
  declare module.exports: any;
}

declare module 'draft-js-compact/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-compact/lib/util' {
  declare module.exports: any;
}

declare module 'draft-js-compact/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-compact/lib/compress.js' {
  declare module.exports: $Exports<'draft-js-compact/lib/compress'>;
}
declare module 'draft-js-compact/lib/expand.js' {
  declare module.exports: $Exports<'draft-js-compact/lib/expand'>;
}
declare module 'draft-js-compact/lib/index.js' {
  declare module.exports: $Exports<'draft-js-compact/lib/index'>;
}
declare module 'draft-js-compact/lib/util.js' {
  declare module.exports: $Exports<'draft-js-compact/lib/util'>;
}
declare module 'draft-js-compact/test/index.js' {
  declare module.exports: $Exports<'draft-js-compact/test/index'>;
}
