// flow-typed signature: d7e92011a76494cb2e78432b05561968
// flow-typed version: <<STUB>>/haikunator_v^2.0.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'haikunator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'haikunator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'haikunator/lib/haikunator' {
  declare module.exports: any;
}

declare module 'haikunator/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'haikunator/lib/haikunator.js' {
  declare module.exports: $Exports<'haikunator/lib/haikunator'>;
}
declare module 'haikunator/test/test.js' {
  declare module.exports: $Exports<'haikunator/test/test'>;
}
