// flow-typed signature: 4275c48acaec002754b4baacb9ad222a
// flow-typed version: <<STUB>>/immutablediff_v^0.4.4/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutablediff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutablediff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immutablediff/gulpfile' {
  declare module.exports: any;
}

declare module 'immutablediff/src/diff' {
  declare module.exports: any;
}

declare module 'immutablediff/src/lcs' {
  declare module.exports: any;
}

declare module 'immutablediff/src/path' {
  declare module.exports: any;
}

declare module 'immutablediff/src/utils' {
  declare module.exports: any;
}

declare module 'immutablediff/tests/comparisonTests.test' {
  declare module.exports: any;
}

declare module 'immutablediff/tests/lcs.test' {
  declare module.exports: any;
}

declare module 'immutablediff/tests/MapDiff.test' {
  declare module.exports: any;
}

declare module 'immutablediff/tests/path.test' {
  declare module.exports: any;
}

declare module 'immutablediff/tests/performance/immutableDiff.perftest' {
  declare module.exports: any;
}

declare module 'immutablediff/tests/performance/veryBigArray' {
  declare module.exports: any;
}

declare module 'immutablediff/tests/primitiveTypeDiff.test' {
  declare module.exports: any;
}

declare module 'immutablediff/tests/sequenceDiff.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immutablediff/gulpfile.js' {
  declare module.exports: $Exports<'immutablediff/gulpfile'>;
}
declare module 'immutablediff/src/diff.js' {
  declare module.exports: $Exports<'immutablediff/src/diff'>;
}
declare module 'immutablediff/src/lcs.js' {
  declare module.exports: $Exports<'immutablediff/src/lcs'>;
}
declare module 'immutablediff/src/path.js' {
  declare module.exports: $Exports<'immutablediff/src/path'>;
}
declare module 'immutablediff/src/utils.js' {
  declare module.exports: $Exports<'immutablediff/src/utils'>;
}
declare module 'immutablediff/tests/comparisonTests.test.js' {
  declare module.exports: $Exports<'immutablediff/tests/comparisonTests.test'>;
}
declare module 'immutablediff/tests/lcs.test.js' {
  declare module.exports: $Exports<'immutablediff/tests/lcs.test'>;
}
declare module 'immutablediff/tests/MapDiff.test.js' {
  declare module.exports: $Exports<'immutablediff/tests/MapDiff.test'>;
}
declare module 'immutablediff/tests/path.test.js' {
  declare module.exports: $Exports<'immutablediff/tests/path.test'>;
}
declare module 'immutablediff/tests/performance/immutableDiff.perftest.js' {
  declare module.exports: $Exports<'immutablediff/tests/performance/immutableDiff.perftest'>;
}
declare module 'immutablediff/tests/performance/veryBigArray.js' {
  declare module.exports: $Exports<'immutablediff/tests/performance/veryBigArray'>;
}
declare module 'immutablediff/tests/primitiveTypeDiff.test.js' {
  declare module.exports: $Exports<'immutablediff/tests/primitiveTypeDiff.test'>;
}
declare module 'immutablediff/tests/sequenceDiff.test.js' {
  declare module.exports: $Exports<'immutablediff/tests/sequenceDiff.test'>;
}
