// flow-typed signature: 0ff9ebbc92e4fc2cd7ab0dd53f3f5297
// flow-typed version: <<STUB>>/immutablepatch_v^0.4.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutablepatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutablepatch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immutablepatch/gulpfile' {
  declare module.exports: any;
}

declare module 'immutablepatch/src/patch' {
  declare module.exports: any;
}

declare module 'immutablepatch/src/path' {
  declare module.exports: any;
}

declare module 'immutablepatch/tests/integration.test' {
  declare module.exports: any;
}

declare module 'immutablepatch/tests/mapPatch.test' {
  declare module.exports: any;
}

declare module 'immutablepatch/tests/path.test' {
  declare module.exports: any;
}

declare module 'immutablepatch/tests/primitiveTypePatch.test' {
  declare module.exports: any;
}

declare module 'immutablepatch/tests/sequencePatch.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immutablepatch/gulpfile.js' {
  declare module.exports: $Exports<'immutablepatch/gulpfile'>;
}
declare module 'immutablepatch/src/patch.js' {
  declare module.exports: $Exports<'immutablepatch/src/patch'>;
}
declare module 'immutablepatch/src/path.js' {
  declare module.exports: $Exports<'immutablepatch/src/path'>;
}
declare module 'immutablepatch/tests/integration.test.js' {
  declare module.exports: $Exports<'immutablepatch/tests/integration.test'>;
}
declare module 'immutablepatch/tests/mapPatch.test.js' {
  declare module.exports: $Exports<'immutablepatch/tests/mapPatch.test'>;
}
declare module 'immutablepatch/tests/path.test.js' {
  declare module.exports: $Exports<'immutablepatch/tests/path.test'>;
}
declare module 'immutablepatch/tests/primitiveTypePatch.test.js' {
  declare module.exports: $Exports<'immutablepatch/tests/primitiveTypePatch.test'>;
}
declare module 'immutablepatch/tests/sequencePatch.test.js' {
  declare module.exports: $Exports<'immutablepatch/tests/sequencePatch.test'>;
}
