// flow-typed signature: 72d2e61bcf96c67d0b8612e0c6781c50
// flow-typed version: <<STUB>>/jsondiffpatch_v^0.3.10/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsondiffpatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsondiffpatch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsondiffpatch/dist/empty' {
  declare module.exports: any;
}

declare module 'jsondiffpatch/dist/jsondiffpatch.cjs' {
  declare module.exports: any;
}

declare module 'jsondiffpatch/dist/jsondiffpatch.esm' {
  declare module.exports: any;
}

declare module 'jsondiffpatch/dist/jsondiffpatch.umd' {
  declare module.exports: any;
}

declare module 'jsondiffpatch/dist/jsondiffpatch.umd.slim' {
  declare module.exports: any;
}

declare module 'jsondiffpatch/dist/jsondiffpatch.umd.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsondiffpatch/dist/empty.js' {
  declare module.exports: $Exports<'jsondiffpatch/dist/empty'>;
}
declare module 'jsondiffpatch/dist/jsondiffpatch.cjs.js' {
  declare module.exports: $Exports<'jsondiffpatch/dist/jsondiffpatch.cjs'>;
}
declare module 'jsondiffpatch/dist/jsondiffpatch.esm.js' {
  declare module.exports: $Exports<'jsondiffpatch/dist/jsondiffpatch.esm'>;
}
declare module 'jsondiffpatch/dist/jsondiffpatch.umd.js' {
  declare module.exports: $Exports<'jsondiffpatch/dist/jsondiffpatch.umd'>;
}
declare module 'jsondiffpatch/dist/jsondiffpatch.umd.slim.js' {
  declare module.exports: $Exports<'jsondiffpatch/dist/jsondiffpatch.umd.slim'>;
}
declare module 'jsondiffpatch/dist/jsondiffpatch.umd.test.js' {
  declare module.exports: $Exports<'jsondiffpatch/dist/jsondiffpatch.umd.test'>;
}
