// flow-typed signature: 33b1a75c972ee88da3e0e5aa895a194c
// flow-typed version: <<STUB>>/lambda-edge-router_v^0.0.13/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lambda-edge-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lambda-edge-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lambda-edge-router/src/index' {
  declare module.exports: any;
}

declare module 'lambda-edge-router/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lambda-edge-router/src/index.js' {
  declare module.exports: $Exports<'lambda-edge-router/src/index'>;
}
declare module 'lambda-edge-router/test/index.js' {
  declare module.exports: $Exports<'lambda-edge-router/test/index'>;
}
