// flow-typed signature: d49e0668551a4115ce1a54fd3a261f76
// flow-typed version: <<STUB>>/monograph_v^0.0.21/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'monograph'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'monograph' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'monograph/lib/convert' {
  declare module.exports: any;
}

declare module 'monograph/lib/convertFromDraftStateToRaw' {
  declare module.exports: any;
}

declare module 'monograph/lib/convertFromRawToDraftState' {
  declare module.exports: any;
}

declare module 'monograph/lib/index' {
  declare module.exports: any;
}

declare module 'monograph/lib/legacy/BaseEditor' {
  declare module.exports: any;
}

declare module 'monograph/lib/legacy/blockRenderMap' {
  declare module.exports: any;
}

declare module 'monograph/lib/legacy/customStyleMap' {
  declare module.exports: any;
}

declare module 'monograph/lib/legacy/Monograph' {
  declare module.exports: any;
}

declare module 'monograph/lib/legacy/PluginsEditor' {
  declare module.exports: any;
}

declare module 'monograph/lib/Monograph/customBlockRenderMap' {
  declare module.exports: any;
}

declare module 'monograph/lib/Monograph/customStyleMap' {
  declare module.exports: any;
}

declare module 'monograph/lib/Monograph/experimental/CustomEditorBlock' {
  declare module.exports: any;
}

declare module 'monograph/lib/Monograph/experimental/CustomToolbar' {
  declare module.exports: any;
}

declare module 'monograph/lib/Monograph/experimental/Portal' {
  declare module.exports: any;
}

declare module 'monograph/lib/Monograph/index' {
  declare module.exports: any;
}

declare module 'monograph/lib/Monograph/initializePlugins' {
  declare module.exports: any;
}

declare module 'monograph/lib/Monograph/keyBindingFn' {
  declare module.exports: any;
}

declare module 'monograph/lib/Monograph/MultiDecorator' {
  declare module.exports: any;
}

declare module 'monograph/lib/Monograph/resolveDecorators' {
  declare module.exports: any;
}

declare module 'monograph/lib/plugins/anchorPlugin/index' {
  declare module.exports: any;
}

declare module 'monograph/lib/plugins/customToolbarPlugin/index' {
  declare module.exports: any;
}

declare module 'monograph/lib/plugins/customToolbarPlugin/InsertImageButton/index' {
  declare module.exports: any;
}

declare module 'monograph/lib/plugins/imagePlugin/ImageComponent' {
  declare module.exports: any;
}

declare module 'monograph/lib/plugins/imagePlugin/index' {
  declare module.exports: any;
}

declare module 'monograph/lib/plugins/imagePlugin/insertImage' {
  declare module.exports: any;
}

declare module 'monograph/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'monograph/lib/plugins/prismPlugin/index' {
  declare module.exports: any;
}

declare module 'monograph/lib/util' {
  declare module.exports: any;
}

declare module 'monograph/src/convert' {
  declare module.exports: any;
}

declare module 'monograph/src/convertFromDraftStateToRaw' {
  declare module.exports: any;
}

declare module 'monograph/src/convertFromRawToDraftState' {
  declare module.exports: any;
}

declare module 'monograph/src/index' {
  declare module.exports: any;
}

declare module 'monograph/src/legacy/BaseEditor' {
  declare module.exports: any;
}

declare module 'monograph/src/legacy/blockRenderMap' {
  declare module.exports: any;
}

declare module 'monograph/src/legacy/customStyleMap' {
  declare module.exports: any;
}

declare module 'monograph/src/legacy/Monograph' {
  declare module.exports: any;
}

declare module 'monograph/src/legacy/PluginsEditor' {
  declare module.exports: any;
}

declare module 'monograph/src/Monograph/customBlockRenderMap' {
  declare module.exports: any;
}

declare module 'monograph/src/Monograph/customStyleMap' {
  declare module.exports: any;
}

declare module 'monograph/src/Monograph/experimental/CustomEditorBlock' {
  declare module.exports: any;
}

declare module 'monograph/src/Monograph/experimental/CustomToolbar' {
  declare module.exports: any;
}

declare module 'monograph/src/Monograph/experimental/Portal' {
  declare module.exports: any;
}

declare module 'monograph/src/Monograph/index' {
  declare module.exports: any;
}

declare module 'monograph/src/Monograph/initializePlugins' {
  declare module.exports: any;
}

declare module 'monograph/src/Monograph/keyBindingFn' {
  declare module.exports: any;
}

declare module 'monograph/src/Monograph/MultiDecorator' {
  declare module.exports: any;
}

declare module 'monograph/src/Monograph/resolveDecorators' {
  declare module.exports: any;
}

declare module 'monograph/src/plugins/anchorPlugin/index' {
  declare module.exports: any;
}

declare module 'monograph/src/plugins/customToolbarPlugin/index' {
  declare module.exports: any;
}

declare module 'monograph/src/plugins/customToolbarPlugin/InsertImageButton/index' {
  declare module.exports: any;
}

declare module 'monograph/src/plugins/imagePlugin/ImageComponent' {
  declare module.exports: any;
}

declare module 'monograph/src/plugins/imagePlugin/index' {
  declare module.exports: any;
}

declare module 'monograph/src/plugins/imagePlugin/insertImage' {
  declare module.exports: any;
}

declare module 'monograph/src/plugins/index' {
  declare module.exports: any;
}

declare module 'monograph/src/plugins/prismPlugin/index' {
  declare module.exports: any;
}

declare module 'monograph/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'monograph/lib/convert.js' {
  declare module.exports: $Exports<'monograph/lib/convert'>;
}
declare module 'monograph/lib/convertFromDraftStateToRaw.js' {
  declare module.exports: $Exports<'monograph/lib/convertFromDraftStateToRaw'>;
}
declare module 'monograph/lib/convertFromRawToDraftState.js' {
  declare module.exports: $Exports<'monograph/lib/convertFromRawToDraftState'>;
}
declare module 'monograph/lib/index.js' {
  declare module.exports: $Exports<'monograph/lib/index'>;
}
declare module 'monograph/lib/legacy/BaseEditor.js' {
  declare module.exports: $Exports<'monograph/lib/legacy/BaseEditor'>;
}
declare module 'monograph/lib/legacy/blockRenderMap.js' {
  declare module.exports: $Exports<'monograph/lib/legacy/blockRenderMap'>;
}
declare module 'monograph/lib/legacy/customStyleMap.js' {
  declare module.exports: $Exports<'monograph/lib/legacy/customStyleMap'>;
}
declare module 'monograph/lib/legacy/Monograph.js' {
  declare module.exports: $Exports<'monograph/lib/legacy/Monograph'>;
}
declare module 'monograph/lib/legacy/PluginsEditor.js' {
  declare module.exports: $Exports<'monograph/lib/legacy/PluginsEditor'>;
}
declare module 'monograph/lib/Monograph/customBlockRenderMap.js' {
  declare module.exports: $Exports<'monograph/lib/Monograph/customBlockRenderMap'>;
}
declare module 'monograph/lib/Monograph/customStyleMap.js' {
  declare module.exports: $Exports<'monograph/lib/Monograph/customStyleMap'>;
}
declare module 'monograph/lib/Monograph/experimental/CustomEditorBlock.js' {
  declare module.exports: $Exports<'monograph/lib/Monograph/experimental/CustomEditorBlock'>;
}
declare module 'monograph/lib/Monograph/experimental/CustomToolbar.js' {
  declare module.exports: $Exports<'monograph/lib/Monograph/experimental/CustomToolbar'>;
}
declare module 'monograph/lib/Monograph/experimental/Portal.js' {
  declare module.exports: $Exports<'monograph/lib/Monograph/experimental/Portal'>;
}
declare module 'monograph/lib/Monograph/index.js' {
  declare module.exports: $Exports<'monograph/lib/Monograph/index'>;
}
declare module 'monograph/lib/Monograph/initializePlugins.js' {
  declare module.exports: $Exports<'monograph/lib/Monograph/initializePlugins'>;
}
declare module 'monograph/lib/Monograph/keyBindingFn.js' {
  declare module.exports: $Exports<'monograph/lib/Monograph/keyBindingFn'>;
}
declare module 'monograph/lib/Monograph/MultiDecorator.js' {
  declare module.exports: $Exports<'monograph/lib/Monograph/MultiDecorator'>;
}
declare module 'monograph/lib/Monograph/resolveDecorators.js' {
  declare module.exports: $Exports<'monograph/lib/Monograph/resolveDecorators'>;
}
declare module 'monograph/lib/plugins/anchorPlugin/index.js' {
  declare module.exports: $Exports<'monograph/lib/plugins/anchorPlugin/index'>;
}
declare module 'monograph/lib/plugins/customToolbarPlugin/index.js' {
  declare module.exports: $Exports<'monograph/lib/plugins/customToolbarPlugin/index'>;
}
declare module 'monograph/lib/plugins/customToolbarPlugin/InsertImageButton/index.js' {
  declare module.exports: $Exports<'monograph/lib/plugins/customToolbarPlugin/InsertImageButton/index'>;
}
declare module 'monograph/lib/plugins/imagePlugin/ImageComponent.js' {
  declare module.exports: $Exports<'monograph/lib/plugins/imagePlugin/ImageComponent'>;
}
declare module 'monograph/lib/plugins/imagePlugin/index.js' {
  declare module.exports: $Exports<'monograph/lib/plugins/imagePlugin/index'>;
}
declare module 'monograph/lib/plugins/imagePlugin/insertImage.js' {
  declare module.exports: $Exports<'monograph/lib/plugins/imagePlugin/insertImage'>;
}
declare module 'monograph/lib/plugins/index.js' {
  declare module.exports: $Exports<'monograph/lib/plugins/index'>;
}
declare module 'monograph/lib/plugins/prismPlugin/index.js' {
  declare module.exports: $Exports<'monograph/lib/plugins/prismPlugin/index'>;
}
declare module 'monograph/lib/util.js' {
  declare module.exports: $Exports<'monograph/lib/util'>;
}
declare module 'monograph/src/convert.js' {
  declare module.exports: $Exports<'monograph/src/convert'>;
}
declare module 'monograph/src/convertFromDraftStateToRaw.js' {
  declare module.exports: $Exports<'monograph/src/convertFromDraftStateToRaw'>;
}
declare module 'monograph/src/convertFromRawToDraftState.js' {
  declare module.exports: $Exports<'monograph/src/convertFromRawToDraftState'>;
}
declare module 'monograph/src/index.js' {
  declare module.exports: $Exports<'monograph/src/index'>;
}
declare module 'monograph/src/legacy/BaseEditor.js' {
  declare module.exports: $Exports<'monograph/src/legacy/BaseEditor'>;
}
declare module 'monograph/src/legacy/blockRenderMap.js' {
  declare module.exports: $Exports<'monograph/src/legacy/blockRenderMap'>;
}
declare module 'monograph/src/legacy/customStyleMap.js' {
  declare module.exports: $Exports<'monograph/src/legacy/customStyleMap'>;
}
declare module 'monograph/src/legacy/Monograph.js' {
  declare module.exports: $Exports<'monograph/src/legacy/Monograph'>;
}
declare module 'monograph/src/legacy/PluginsEditor.js' {
  declare module.exports: $Exports<'monograph/src/legacy/PluginsEditor'>;
}
declare module 'monograph/src/Monograph/customBlockRenderMap.js' {
  declare module.exports: $Exports<'monograph/src/Monograph/customBlockRenderMap'>;
}
declare module 'monograph/src/Monograph/customStyleMap.js' {
  declare module.exports: $Exports<'monograph/src/Monograph/customStyleMap'>;
}
declare module 'monograph/src/Monograph/experimental/CustomEditorBlock.js' {
  declare module.exports: $Exports<'monograph/src/Monograph/experimental/CustomEditorBlock'>;
}
declare module 'monograph/src/Monograph/experimental/CustomToolbar.js' {
  declare module.exports: $Exports<'monograph/src/Monograph/experimental/CustomToolbar'>;
}
declare module 'monograph/src/Monograph/experimental/Portal.js' {
  declare module.exports: $Exports<'monograph/src/Monograph/experimental/Portal'>;
}
declare module 'monograph/src/Monograph/index.js' {
  declare module.exports: $Exports<'monograph/src/Monograph/index'>;
}
declare module 'monograph/src/Monograph/initializePlugins.js' {
  declare module.exports: $Exports<'monograph/src/Monograph/initializePlugins'>;
}
declare module 'monograph/src/Monograph/keyBindingFn.js' {
  declare module.exports: $Exports<'monograph/src/Monograph/keyBindingFn'>;
}
declare module 'monograph/src/Monograph/MultiDecorator.js' {
  declare module.exports: $Exports<'monograph/src/Monograph/MultiDecorator'>;
}
declare module 'monograph/src/Monograph/resolveDecorators.js' {
  declare module.exports: $Exports<'monograph/src/Monograph/resolveDecorators'>;
}
declare module 'monograph/src/plugins/anchorPlugin/index.js' {
  declare module.exports: $Exports<'monograph/src/plugins/anchorPlugin/index'>;
}
declare module 'monograph/src/plugins/customToolbarPlugin/index.js' {
  declare module.exports: $Exports<'monograph/src/plugins/customToolbarPlugin/index'>;
}
declare module 'monograph/src/plugins/customToolbarPlugin/InsertImageButton/index.js' {
  declare module.exports: $Exports<'monograph/src/plugins/customToolbarPlugin/InsertImageButton/index'>;
}
declare module 'monograph/src/plugins/imagePlugin/ImageComponent.js' {
  declare module.exports: $Exports<'monograph/src/plugins/imagePlugin/ImageComponent'>;
}
declare module 'monograph/src/plugins/imagePlugin/index.js' {
  declare module.exports: $Exports<'monograph/src/plugins/imagePlugin/index'>;
}
declare module 'monograph/src/plugins/imagePlugin/insertImage.js' {
  declare module.exports: $Exports<'monograph/src/plugins/imagePlugin/insertImage'>;
}
declare module 'monograph/src/plugins/index.js' {
  declare module.exports: $Exports<'monograph/src/plugins/index'>;
}
declare module 'monograph/src/plugins/prismPlugin/index.js' {
  declare module.exports: $Exports<'monograph/src/plugins/prismPlugin/index'>;
}
declare module 'monograph/src/util.js' {
  declare module.exports: $Exports<'monograph/src/util'>;
}
