// flow-typed signature: a4cd5b7517bb196e5be15ebf11701b02
// flow-typed version: <<STUB>>/simple-cache-provider_v^0.5.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-cache-provider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-cache-provider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-cache-provider/cjs/simple-cache-provider.development' {
  declare module.exports: any;
}

declare module 'simple-cache-provider/cjs/simple-cache-provider.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-cache-provider/cjs/simple-cache-provider.development.js' {
  declare module.exports: $Exports<'simple-cache-provider/cjs/simple-cache-provider.development'>;
}
declare module 'simple-cache-provider/cjs/simple-cache-provider.production.min.js' {
  declare module.exports: $Exports<'simple-cache-provider/cjs/simple-cache-provider.production.min'>;
}
declare module 'simple-cache-provider/index' {
  declare module.exports: $Exports<'simple-cache-provider'>;
}
declare module 'simple-cache-provider/index.js' {
  declare module.exports: $Exports<'simple-cache-provider'>;
}
