// flow-typed signature: 1ac9f2fdfafde04789fb586e8fd13326
// flow-typed version: <<STUB>>/with-async-component_v^0.0.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'with-async-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'with-async-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'with-async-component/lib/index' {
  declare module.exports: any;
}

declare module 'with-async-component/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'with-async-component/lib/index.js' {
  declare module.exports: $Exports<'with-async-component/lib/index'>;
}
declare module 'with-async-component/src/index.js' {
  declare module.exports: $Exports<'with-async-component/src/index'>;
}
