// app
export const SELECT_POST = 'SELECT_POST'
export const UPDATE_POST_TITLE = 'UPDATE_POST_TITLE'
export const UPDATE_VARIABLES = 'UPDATE_VARIABLES'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'

// editor
export const HYDRATE_EDITOR_STATE = 'HYDRATE_EDITOR_STATE'
export const UPDATE_EDITOR_STATE = 'UPDATE_EDITOR_STATE'
export const UPDATE_STATUS = 'UPDATE_STATUS'
export const DISPATCH = 'DISPATCH'
export const SET_DIALOG_STATE = 'SET_DIALOG_STATE'
